app/api/urls.py
from django.urls import path, re_path
from api import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

app_name = 'api'

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('rates/', views.RatesViews.as_view(), name='rates'),
    path('rates/<int:pk>/', views.RatesDetailsView.as_view(), name='rates_details'),

    path('sources/', views.SourcesViews.as_view(), name='sources'),

    path('contacts/', views.ContactsViews.as_view(), name='contacts'),
    path('contacts/<int:pk>/', views.ContactsDetailsView.as_view(), name='contacts_details'),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

app/currency/urls.py
from django.urls import path
from currency import views

app_name = 'currency'

urlpatterns = [

    path('rate/', views.RateListView.as_view(), name='rate_list'),
    path('rate/rate_create/', views.RateCreateView.as_view(), name='rate_create'),
    path('rate/update/<int:pk>/', views.RateUpdateView.as_view(), name='rate_update'),
    path('rate/delete/<int:pk>/', views.RateDeleteView.as_view(), name='rate_delete'),
    path('rate/details/<int:pk>/', views.RateDetailsView.as_view(), name='rate_details'),

    path('contact_base/', views.ContactBaseView.as_view(), name='contact_base'),
    path('contact_base/create/', views.ContactUsCreateView.as_view(), name='base_create'),

    path('source/', views.SourceDataView.as_view(), name='source'),
    path('source/create/', views.SourceCreateView.as_view(), name='source_create'),
    path('source/update/<int:pk>/', views.SourceUpdateView.as_view(), name='source_update'),
    path('source/delete/<int:pk>/', views.SourceDeleteView.as_view(), name='source_delete'),

    path('response_log/', views.ResponseLogView.as_view(), name='response_log'),

    path('my_profile/<int:pk>', views.UserProfileView.as_view(), name='my_profile'),

]

app/settings/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from currency import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('django.contrib.auth.urls')),

    path('', views.IndexView.as_view(), name='index'),
    path('silk/', include('silk.urls', namespace='silk')),

    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),

]

urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

app/currency/models.py
from django.db import models
from datetime import datetime


class ContactUs(models.Model):
    email_to = models.EmailField(max_length=254)
    email_from = models.EmailField(max_length=254)
    subject = models.CharField(max_length=200)
    massage = models.CharField(max_length=500)


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    logo = models.FileField(default='av.png')


class Rate(models.Model):
    base_currency_type = models.CharField(max_length=3)
    currency_type = models.CharField(max_length=3)
    sale = models.DecimalField(max_digits=10, decimal_places=4)
    buy = models.DecimalField(max_digits=10, decimal_places=4)
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE, related_name='rates')
    created = models.CharField(max_length=30, default=f"{datetime.now():%d.%m.%Y}")


class ResponseLog (models.Model):
    response_time = models.CharField(max_length=64)
    request_method = models.CharField(max_length=64)
    query_params = models.CharField(max_length=64)
    ip = models.CharField(max_length=64)
    path = models.CharField(max_length=64)

app/currency/forms.py
from django import forms
from currency.models import Rate, Source, ContactUs


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'base_currency_type',
            'currency_type',
            'sale',
            'buy',
            'source',
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'source_url',
            'name',
            'logo',
        )


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_to',
            'email_from',
            'subject',
            'massage',
        )

app/currency/views.py
from django.contrib.auth import get_user_model
from django import forms
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django_filters.views import FilterView

from currency.filters import RateFilter
from currency.models import ContactUs, Rate, Source, ResponseLog
from currency.forms import RateForm, SourceForm, ContactUsForm

from currency.tasks import send_contact_us_email


class IndexView(generic.TemplateView):
    template_name = 'index.html'


class ContactBaseView(generic.ListView):
    queryset = ContactUs.objects.all()
    template_name = 'contact_base.html'


class ContactUsCreateView(generic.CreateView):
    queryset = ContactUs.objects.all()
    template_name = 'create_new_massage.html'
    form_class = ContactUsForm
    success_url = reverse_lazy('currency:contact_base')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['massage'].widget = forms.Textarea()
        return form

    def form_valid(self, form):
        response = super().form_valid(form)

        send_contact_us_email.delay(self.object.subject, self.object.email_from)

        return response


class RateListView(FilterView):
    queryset = Rate.objects.all().select_related('source')
    template_name = 'rate_list.html'
    paginate_by = 10
    filterset_class = RateFilter
    page_size_options = ['4', '8', '12', '24', '36', '100']

    def get_context_data(self, *args, **kwargs):
        context: dict = super().get_context_data(*args, **kwargs)
        filters_params = self.request.GET.copy()

        if self.page_kwarg in filters_params:
            del filters_params[self.page_kwarg]

        context['filters_params'] = filters_params.urlencode()
        context['page_size'] = self.get_paginate_by()
        context['page_size_options'] = self.page_size_options

        return context

    def get_paginate_by(self, queryset=None):
        if self.request.GET.get('page_size') in self.page_size_options:
            paginate_by = self.request.GET['page_size']
        else:
            paginate_by = self.paginate_by

        return paginate_by


class RateCreateView(generic.CreateView):
    queryset = Rate.objects.all()
    template_name = 'rate_create-update.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


class RateUpdateView(generic.UpdateView):
    queryset = Rate.objects.all()
    template_name = 'rate_create-update.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


class RateDeleteView(UserPassesTestMixin, generic.DeleteView):
    queryset = Rate.objects.all()
    template_name = 'for_delete.html'
    success_url = reverse_lazy('currency:rate_list')

    def test_func(self):
        return self.request.user.is_superuser


class RateDetailsView(generic.DeleteView):
    queryset = Rate.objects.all()
    template_name = 'for_details.html'


class SourceDataView(generic.ListView):
    queryset = Source.objects.all()
    template_name = 'source_data.html'


class SourceCreateView(generic.CreateView):
    queryset = Source.objects.all()
    template_name = 'source_create-update.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source')


class SourceUpdateView(generic.UpdateView):
    queryset = Source.objects.all()
    template_name = 'source_create-update.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source')


class SourceDeleteView(generic.DeleteView):
    queryset = Source.objects.all()
    template_name = 'for_delete.html'
    success_url = reverse_lazy('currency:source')


class ResponseLogView(generic.ListView):
    queryset = ResponseLog.objects.all()
    template_name = 'response_log.html'


class UserProfileView(LoginRequiredMixin, generic.UpdateView):
    queryset = get_user_model().objects.all()
    template_name = 'my_profile.html'
    success_url = reverse_lazy('index')
    fields = (
        'first_name',
        'last_name',
        'avatar',
    )

    def get_object(self, queryset=None):
        return self.request.user

app/currency/templates/contact_base.html
{% extends 'base.html' %}

{% block main_content %}
    <div>
       <a class="btn btn-primary"
       role="button"
       href="{% url 'currency:base_create' %}">Create new massage</a>
    </div>

    <table class="table table-striped">
        <thead >
              <tr>
                <th>Id</th>
                <th>Email_to</th>
                <th>Email_from</th>
                <th>Subject</th>
                <th>Massage</th>
              </tr>
        </thead>
        <tbody>
          {% for data in object_list %}
              <tr>
                <th>{{data.id}}</th>
                <td>{{data.email_to}}</td>
                <td>{{data.email_from}}</td>
                <td>{{data.subject}}</td>
                <td>{{data.massage}}</td>
               </tr>
          {% endfor %}
        </tbody>
    </table>

{% endblock main_content %}

app/currency/templates/create_new_massage.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title%} CREATE {% endblock title%}

{% block main_content%}

    <form method="post">
        {%csrf_token%}
        {{form.email_to|as_crispy_field}}
        {{form.email_from|as_crispy_field}}
        {{form.subject|as_crispy_field}}
        {{form.massage|as_crispy_field}}

        <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/for_create.html
{% extends 'base.html' %}

{% block title%} CREATE {% endblock title%}

{% block main_content%}


    Create

    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/for_delete.html
{% extends 'base.html' %}

{% block title%} DELETE {% endblock title%}

{% block main_content%}
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <div>Do you want to delete?</div>
        <button type="submit">Delete</button>
    </form>
{% endblock main_content %}

app/currency/templates/for_details.html
{% extends 'base.html' %}

{% block title %}RATE DETAILS{% endblock title %}

{% block main_content %}
    <div>ID: {{ rate.id }}</div>
    <div>Buy: {{ rate.buy }}</div>
    <div>Sale: {{ rate.sale }}</div>

{% endblock main_content %}

app/currency/templates/for_update.html
{% extends 'base.html' %}

{% block title%} UPDATE {% endblock title%}

{% block main_content%}

    Update

    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Send</button>
        <button type="reset">Reset</button>
    </form>
{% endblock main_content %}

app/currency/templates/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.previous_page_number }}&{{ filters_params }}">Previous</a></li>
        {% endif %}

        {% for page_num in page_obj.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}&{{ filters_params }}">{{ page_num }}</a></li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ filters_params }}">Next</a></li>
        {% endif %}
    </ul>
</nav>

app/currency/templates/rate_create.html
{% extends 'base.html' %}

{% block main_content%}
    Hi!
{% endblock main_content %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}

{% block title%} DELETE {% endblock title%}

{% block main_content%}
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <div>Do you want to delete?</div>
        <button type="submit">Delete</button>
    </form>
{% endblock main_content %}

app/currency/templates/rate_list.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}
    <div>
       <a class="btn btn-primary"
       role="button"
       href="{% url 'currency:rate_create' %}">Create new rate</a>
    </div>

<form method="get">
        {{ filter.form.as_p }}
        <label for="id-page_size">Items per page</label>
        <select name="page_size" id="id-page_size">
            {% for page_size_option in page_size_options %}
                 <option value="{{ page_size_option }}"
                         {% if page_size == page_size_option %}selected{% endif %}>
                     {{ page_size_option }}
                 </option>
            {% endfor %}
        </select>
        <button type="submit">Filter</button>
</form>


    <table class="table table-dark table-hover">
        <thead >
            <tr>
              <th>ID</th>
              <th>Sale</th>
              <th>Buy</th>
              <th>Base Type</th>
              <th>Type</th>
              <th>Source</th>
              <th>Created</th>
              <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for rate in rate_list %}
          <tr>
              <td>{{ rate.id }}</td>
              <td>{{ rate.sale }}</td>
              <td>{{ rate.buy }}</td>
              <td>{{ rate.base_currency_type }}</td>
              <td>{{ rate.currency_type }}</td>
              <td>{{ rate.source.name }}<img src="{{ rate.source.logo.url }}" height="25" width="25"></td>
              <td>{{ rate.created }}</td>
              <td>
                  <a href="{% url 'currency:rate_details' rate.id %}">view details</a>
                  <a href="{% url 'currency:rate_update' pk=rate.id %}">edit</a>
                  <a href="{% url 'currency:rate_delete' rate.id %}">delete</a>
              </td>
          </tr>
        {% endfor %}
        </tbody>
    </table>


    {% include 'pagination.html' %}
{% endblock main_content %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}

{% block title%} UPDATE {% endblock title%}

{% block main_content%}

    Update

    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Send</button>
        <button type="reset">Reset</button>
    </form>
{% endblock main_content %}

app/currency/templates/response_log.html
{% extends 'base.html' %}

{% block main_content %}

    <table>
      <tr>
        <th>Id</th>
        <th>Response_time</th>
        <th>Request_method</th>
        <th>Query_params</th>
        <th>Ip</th>
        <th>Path</th>
      </tr>
      {% for object in object_list %}
          <tr>
            <th>{{object.id}}</th>
            <td>{{object.response_time}}</td>
            <td>{{object.request_method}}</td>
            <td>{{object.query_params}}</td>
            <td>{{object.ip}}</td>
            <td>{{object.path}}</td>

          </tr>
      {% endfor %}
    </table>

{% endblock main_content %}

app/currency/templates/source_create-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main_content%}
    Create

    <form method="post">
        {%csrf_token%}
        {{form.source_url|as_crispy_field}}
        {{form.name|as_crispy_field}}
        {{form.logo|as_crispy_field}}

        <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/source_data.html
{% extends 'base.html' %}

{% block main_content %}
<a class="btn btn-primary"
   role="button"
   href="{% url 'currency:source_create' %}">Create new rate</a>
<div class="container mt-3">
        <h2>Rates List</h2>
    <table class="table table-dark table-hover">

      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Source URL</th>
        <th>Logo</th>
        <th>Options</th>
      </tr>
      {% for source in source_list %}
          <tr>
            <th>{{source.id}}</th>
            <td>{{source.name}}</td>
            <td>{{source.source_url}}</td>
            <td><img src="{{ source.logo.url }}" height="30" width="30"></td>
            <td>
                <a href="{% url 'currency:source_update' source.id %}"> update </a>
                <a href="{% url 'currency:source_delete' source.id %}"> delete </a>
            </td>
          </tr>
      {% endfor %}
    </table>

{% endblock main_content %}